version: '3.8'

services:
  ups-db:
    image: postgres:13
    container_name: ups-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ups_db_data:/var/lib/postgresql/data
      - ./db/UPS_db.sql:/docker-entrypoint-initdb.d/init.sql
    # networks:
    #   - ups-net

  ups:
    build:
      context: .
    container_name: ups-server
    depends_on:
      - ups-db
    restart: always
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WORLD_HOST: ${WORLD_HOST}
      WORLD_PORT: ${WORLD_PORT}
      AMAZON_URL: ${AMAZON_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./ups:/app
    # networks:
    #   - ups-net
    command:  >
      sh -c "
        echo '🚀 Starting Django: running makemigrations...' &&
        python manage.py makemigrations core &&
        echo '✅ makemigrations done. Now migrating...' &&
        python manage.py migrate &&
        echo '✅ migrate done. Starting Django server...' &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  ups_db_data:

# networks:
#   ups-net:
#     external: true