# Generated by Django 3.2.25 on 2025-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=50)),
                ('message_content', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amazon_messages',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seqnum', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'error_logs',
            },
        ),
        migrations.CreateModel(
            name='SequenceNum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_seq_num', models.BigIntegerField(default=0)),
                ('last_ack_received', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sequence_num',
            },
        ),
        migrations.CreateModel(
            name='WorldState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('world_id', models.BigIntegerField(unique=True)),
                ('sim_speed', models.IntegerField(default=100)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wrold_state',
            },
        ),
    ]
