# Generated by Django 3.2.25 on 2025-04-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_amazonmessage_errorlog_sequencenum_worldstate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worldstate',
            table='world_state',
        ),
    ]
