# Generated by Django 3.2.25 on 2025-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_worldstate_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq_num', models.BigIntegerField()),
                ('command_type', models.CharField(max_length=20)),
                ('command_data', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'command_logs',
            },
        ),
        migrations.CreateModel(
            name='CommandRetryQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_seq_num', models.BigIntegerField()),
                ('retry_count', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'command_retry_queue',
            },
        ),
    ]
