# Generated by Django 3.2.25 on 2025-04-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_commandlog_commandretryqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldstate',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
