# Generated by Django 3.2.25 on 2025-04-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_worldstate_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
