# Generated by Django 3.2.25 on 2025-04-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250426_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='y',
            field=models.IntegerField(null=True),
        ),
    ]
